name: Linting and Testing CI

on:
  pull_request:
    branches:
      - main
      - dev-AI
      - dev

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('AI/python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r AI/python/requirements.txt
      - name: Run Pylint
        run: python3 -m pylint --rcfile=AI/python/.pylintrc AI/python/*.py || true

      - name: Run Flake8
        run: python3 -m flake8 AI/python/ --config=AI/python/.flake8

  test-python:
    name: Test Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('AI/python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r AI/python/requirements.txt
      - name: Run Python Scripts
        run: |
          for script in AI/python/*.py; do
            if [[ -f "$script" && "$script" != *"__init__.py" ]]; then
              echo "Running $script"
              python3 "$script" || { echo "Script $script failed"; exit 1; }
            fi
          done